/**
 * chart-studio — headless charting primitives for React.
 *
 * A headless, composable charting library for chart state, filtering,
 * grouping, metrics, transformed data, and model-aware dashboards.
 * Pass raw data for the zero-config path, or add an explicit dataset and
 * chart schema when you want full control over inference overrides, derived
 * columns, and selectable chart controls.
 *
 * @example
 * ```tsx
 * import { defineDataset, useChart } from '@matthieumordrel/chart-studio'
 * import { Chart, ChartToolbar, ChartCanvas } from '@matthieumordrel/chart-studio-ui'
 *
 * const dataset = defineDataset<Row>()
 *   .columns((c) => [
 *     c.date('dateAdded', { label: 'Date Added' }),
 *     c.category('ownerName', { label: 'Consultant' }),
 *     c.number('salary', { format: 'currency' }),
 *   ])
 *
 * const schema = dataset.chart('myChart')
 *
 * function MyChart({ data }) {
 *   const chart = useChart({ data, schema })
 *   return (
 *     <Chart chart={chart}>
 *       <ChartToolbar />
 *       <ChartCanvas />
 *     </Chart>
 *   )
 * }
 * ```
 */

// Headless charting API.
export {
  CHART_TYPE_CONFIG,
  DATE_RANGE_PRESETS,
  autoFilterForBucket,
  resolvePresetFilter,
  getPresetLabel,
  defineDataModel,
  defineDashboard,
  defineDataset,
  inferColumnsFromData,
  useChart,
  useDashboard,
  useDashboardChart,
  useDashboardContext,
  useDashboardDataset,
  useDashboardSharedFilter,
  DashboardProvider,
  validateDatasetData,
  getSeriesColor,
  buildColorMap,
  runPipeline,
  applyFilters,
  extractAvailableFilters,
  buildAvailableMetrics,
  getMetricLabel,
  resolveDashboardDefinition,
  DATA_LABEL_DEFAULTS,
  resolveShowDataLabels,
  computeDateRange,
  filterByDateRange,
} from './core/index.js'

export type {
  DataModelDefinition,
  DataModelBuilder,
  DefinedDataModel,
  DefinedMaterializedView,
  KeyedDatasetDefinition,
  MaterializedProjectableColumnId,
  MaterializedViewDefinition,
  MaterializedViewMetadata,
  MaterializedViewStepMetadata,
  ModelAssociationDefinition,
  ModelAttributeDefinition,
  ModelDataInput,
  ModelMaterializationBuilder,
  ModelMaterializationStartBuilder,
  ModelDatasetId,
  ModelRelationshipDefinition,
  ResolvedDataModelFromDefinition,
  SelectAttributeConfig,
  DashboardBuilder,
  DashboardChartIdFromDefinition,
  DashboardChartInstanceFromDefinition,
  DashboardDataInputFromDefinition,
  DashboardDatasetIdFromDefinition,
  DashboardDatasetRowsFromDefinition,
  DashboardDateRangeSelection,
  DashboardDefinition,
  DashboardLocalSharedSelectFilterConfig,
  DashboardResolvedChart,
  DashboardResolvedChartOwnership,
  DashboardRuntime,
  DashboardSharedDateRangeFilterConfig,
  DashboardSharedDateRangeFilterDefinition,
  DashboardSharedDateRangeFilterRuntime,
  DashboardSharedDateRangePresetId,
  DashboardSharedFilterDefinition,
  DashboardSharedFilterIdFromDefinition,
  DashboardSharedFilterRuntime,
  DashboardSharedFilterRuntimeFromDefinition,
  DashboardSharedFilters,
  DashboardSharedSelectFilterRuntime,
  DashboardSharedSelectTarget,
  DashboardSharedDateRangeTarget,
  DefinedDashboard,
  ResolvedDashboardFromDefinition,
  DatasetBuilder,
  DatasetChartBuilder,
  DatasetChartDefinition,
  DatasetDefinition,
  DatasetKey,
  DatasetRow,
  DefinedDatasetChartSchema,
  DefinedDataset,
  SingleDatasetKeyId,
  ChartSourceOptions,
  ChartAxisType,
  ChartTypeCapabilities,
  UseChartOptions,
  PipelineInput,
  PipelineOutput,
  ChartColumn,
  ChartColumnType,
  ColumnFormat,
  ColumnFormatPreset,
  NumberColumnFormat,
  DateColumnFormat,
  DurationColumnFormat,
  RawColumnSchemaFor,
  RawColumnSchemaMap,
  DerivedColumnSchema,
  DerivedDateColumnSchema,
  DerivedCategoryColumnSchema,
  DerivedBooleanColumnSchema,
  DerivedNumberColumnSchema,
  ChartSchema,
  ChartSchemaDefinition,
  DefinedChartSchema,
  ValidatedChartSchema,
  InferableFieldKey,
  ResolvedColumnIdFromSchema,
  SelectableControlConfig,
  XAxisConfig,
  GroupByConfig,
  FiltersConfig,
  MetricConfig,
  ChartTypeConfig,
  TimeBucketConfig,
  RestrictedXAxisColumnIdFromSchema,
  RestrictedGroupByColumnIdFromSchema,
  RestrictedFilterColumnIdFromSchema,
  RestrictedMetricFromSchema,
  RestrictedChartTypeFromSchema,
  RestrictedTimeBucketFromSchema,
  DateColumn,
  CategoryColumn,
  BooleanColumn,
  NumberColumn,
  ChartType,
  TimeSeriesChartType,
  CategoricalChartType,
  TimeBucket,
  AggregateFunction,
  NumericAggregateFunction,
  NumericAggregateSelection,
  CountMetric,
  AggregateMetric,
  AggregateMetricAllowance,
  Metric,
  MetricAllowance,
  FilterState,
  ChartControlMode,
  ChartDataScopeControlState,
  ChartDataScopeInputs,
  ChartDataScopeInputsFromSchemaDefinition,
  ChartDateRangeSelection,
  SortDirection,
  SortConfig,
  DateRange,
  DateRangeFilter,
  DateRangePresetId,
  MultiSourceChartInstance,
  MultiSourceChartDataScopeInputs,
  ChartSeries,
  TransformedDataPoint,
  AvailableFilter,
  ChartInstance,
  ChartInstanceFromSchema,
  ChartInstanceFromSchemaDefinition,
} from './core/index.js'
